**Welcome to numPy tutorial**

In [1]:
import numpy as np

In [2]:
myarr=np.array([[2,3,4,5,7]],np.int64)

In [3]:
myarr

array([[2, 3, 4, 5, 7]], dtype=int64)

In [4]:
myarr.dtype

dtype('int64')

In [5]:
myarr.shape

(1, 5)

In [6]:
myarr[0]

array([2, 3, 4, 5, 7], dtype=int64)

In [7]:
myarr[0,3]

5

In [8]:
myarr[0,3]=45

In [9]:
myarr

array([[ 2,  3,  4, 45,  7]], dtype=int64)

**Array structure: conversion from other Python structures**

In [10]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
listarray.dtype

dtype('int32')

In [13]:
listarray.shape

(3, 3)